org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false


minecraft_version=1.20.1

minecraft_version_range=[1.20.1]

forge_version=47.3.0

forge_version_range=[47,)

loader_version_range=[47,)

mapping_channel=parchment

mapping_version=2023.09.03-1.20.1

## Mod Properties
curios_version=5.14.1+1.20.1

jei_version=15.8.2.26

irons_spells_version=1.20.1-3.16.2
irons_lib_version=1.20.1-2.1.0

mixin_version=0.8.5

mod_id=reforgeable
mod_name=Reforgeable
mod_license=All Rights Reserved
mod_version=1.2.1-1.20.1
mod_group_id=net.gobies.reforgeable
mod_authors=gobies
mod_description=Adds qualities to tools and armor to give them differentiating stat increases!