
modLoader="javafml"
loaderVersion = "${loader_version_range}"
license = "All Rights Reserved"

[[mixins]]
config = "reforgeable.mixins.json"

[[mods]]
modId="reforgeable"
version="1.0.5-1.21.1"
displayName="Reforgeable"
authors="gobies"
description='''Adds qualities to tools and armor to give them differentiating stat increases!'''

[[dependencies.reforgeable]]
modId="neoforge"
mandatory= true
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.reforgeable]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side= "BOTH"

[modproperties.reforgeable]
configuredBackground="minecraft:textures/block/stone_bricks.png"